### ISSUE TITLE
Could we move ElasticDragDismissLayoutParentChecker into the delegate?

### ISSUE THREAD

**Issue by desertjim** [Commit451/ElasticDragDismissLayout#1]
Hi.  This project looks cool.  

I noticed while looking at the code that ElasticDragDismissLayoutParentChecker is required right before initializing the delegate.  I think this could accidentally be left out, especially if someone were to roll their own custom view group.  I think this check would be beneficial to be located in the init method of the delegate.  

Would you be open to accepting a PR with this change?

**Comment by Jawnnypoo** [comment]
Hey there @desertjim . You make a good point! Not really sure why I didn't put it in the delegate... it would totally make sense to move it there to assure it is enforced properly. Thanks for taking a look and determining that. Yes, I would love to see a PR with the change, if you don't mind, can you make it against the `develop` branch? Much appreciated :+1:

**Comment by desertjim** [comment]
Thanks :)

**Comment by Jawnnypoo** [comment]
Thanks to you! This is now present in 1.0.1
