### ISSUE TITLE
Sample gif in readme broken

### ISSUE THREAD

**Issue by wasdennnoch** [Commit451/ElasticDragDismissLayout#6]
When I open this link in Firefox, I only get the text "Content length exceeded".

**Comment by Jawnnypoo** [comment]
Thanks for reporting! Fixed

**Comment by rashmigottipati** [comment]
I have the same issue. I have a gif URL (uploaded on Dropbox) in README.md and when I try to view the readme file in safari or chrome, it doesn't have the rendered gif. And when I click on the link, it displays the message "content length exceeded"

**Comment by bonyadmitr** [comment]
Some with gif from medium.com

**Comment by vdatasci** [comment]
I have the same problem in a README.md.

**Comment by yash2code** [comment]
+1

**Comment by PAN001** [comment]
+1

**Comment by ahmadawais** [comment]
Still having this issue.

**Comment by MaveyMa** [comment]
+1

**Comment by MelbourneDeveloper** [comment]
Some people say this is fixed when we upload the gif as part of our repo, but I want to know what the limit is when the gid is hosted on another server. And why is there a limit?

**Comment by ksreyr** [comment]
i have the same issue yet

**Comment by lis-r-barreto** [comment]
I have the same issue

**Comment by Obada2020** [comment]
I have the same issue

**Comment by Obada2020** [comment]
+1 😢
